[paths]
# All relative paths are resolved from this settings.ini file.
raw_dir = data/raw
topography_dir = data/topography
satellite_dir = data/satellite
processed_dir = data/processed
results_dir = results

[files]
#
#PRO_20250718_1_100_combined.nc

pro_file = PRO_20250629_100_combined.nc
topography_file = Copernicus_90m_merged.tif
satellite_file = satellite_tirol_3857.tif

[pipeline]
map_script = code/map.py
map_settings_arg = --settings

[plot]
mode = 2d
variable = w

[plot2d]
z_min = 500
z_max = 3200
vertical_every_n = 2
wind_every_n = 3
use_dem_topography = true
first_panel_var = w
